CRAWLING_KONFIGURASI = {
    'MAKS_KEDALAMAN': 3,
    'MAKS_HALAMAN_PER_DOMAIN': 100,
    'JEDA_ANTAR_PERMINTAAN': 2,  # dalam detik
    'HORMATI_ROBOTS_TXT': True,
    'IKUTI_REDIRECTS': True,
    'MAKS_REDIRECTS': 5,
    'ABAIKAN_FRAGMENT': True
}

